import "bootstrap/dist/css/bootstrap.min.css";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/common/Header";
import Footer from "@/common/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Server Component Fundamentals",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
      <html lang="en">
      <body>
      <div style={{ overflow: "hidden" }}>
        <header className="header">
          <div className="container-main">
            <Header />
          </div>
        </header>
      </div>
      {children}
      <Footer />
      </body>
      </html>
  );
}
